//OrdersReducer
export const RESET_ORDER_STATE = 'RESET_ORDER_STATE';
export const ORDERS_REQUEST_LOADING = 'ORDERS_REQUEST_LOADING';

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS';
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL';

export const MY_ORDER_DETAILS_SUCCESS = 'MY_ORDER_DETAILS_SUCCESS';
export const MY_ORDER_DETAILS_FAIL = 'MY_ORDER_DETAILS_FAIL';

//OrderDetails Reducer
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAIL = 'GET_ORDER_DETAILS_FAIL';
